# hf-cache.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tms-hf-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: tms-hf-cache-pv

